package com.rostagabor.mathmaze.utils

/**
 *   IF THE NAME OF THE EXCEPTIONS CHANGES, THE FRONTEND WILL HAVE TO BE UPDATED AS WELL!
 */

/**
 *   Exception for when a username is in an invalid format.
 */
class UsernameInvalidFormatException : Exception()

/**
 *   Exception for when an email is in an invalid format.
 */
class EmailInvalidFormatException : Exception()

/**
 *   Exception for when a password is in an invalid format.
 */
class PasswordInvalidFormatException : Exception()


/**
 *   Exception for when a username is not unique.
 */
class UsernameNotUniqueException : Exception()

/**
 *   Exception for when an email is not unique.
 */
class EmailNotUniqueException : Exception()


/**
 *   Exception for when a user is not found with the given credentials.
 */
class InvalidCredentialsException : Exception()


/**
 *   Exception for when a user is not found with the given email.
 */
class UserNotFoundException : Exception()

/**
 *   Exception for when a token is invalid or expired.
 */
class TokenInvalidOrExpiredException : Exception()


/**
 *   Exception for when a maze dimension is invalid.
 */
class InvalidMazeDimensionException : Exception()

/**
 *   Exception for when a path range is invalid.
 */
class InvalidPathRangeException : Exception()

/**
 *   Exception for when a numbers range is invalid.
 */
class InvalidNumbersRangeException : Exception()


/**
 *   Exception for when a maze is not found with the given id.
 */
class InvalidMazeIdException : Exception()

/**
 *   Exception for when the given rotation is invalid (not 0, 90, 180 or 270).
 */
class InvalidRotationException : Exception()

/**
 *   Exception for when a maze is not recognised in the image.
 */
class CouldNotRecogniseMazeException : Exception()


/**
 *   Exception for when a nickname is in an invalid format.
 */
class NicknameInvalidFormatException : Exception()

/**
 *   Exception for when a nickname is not unique.
 */
class NicknameNotUniqueException : Exception()

/**
 *   Exception for when a path is invalid (the start point or the end point are not in the path).
 */
class InvalidPathException : Exception()


/**
 *   Exception for when a maze was not generated by the user.
 */
class MazeOwnerException : Exception()

/**
 *   Exception for when a description is in an invalid format.
 */
class DescriptionInvalidFormatException : Exception()

/**
 *   Exception for when a location is in an invalid format.
 */
class LocationInvalidFormatException : Exception()

/**
 *   Exception for when a location is not unique.
 */
class LocationNotUniqueException : Exception()

/**
 *   Exception for when a location is not found.
 */
class LocationNotFoundException : Exception()
