name: Unit Tests for Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tests:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Run unit tests
      run: ./gradlew test

    - name: Upload test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: backend/build/reports/tests/test/
